name: macOS Build Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@master
      with:
        repository: wolfssl/wolfssl
        path: wolfssl
    - name: brew
      run: brew install automake libtool  
    - name: wolfssl autogen
      working-directory: ./wolfssl        
      run: ./autogen.sh
    - name: wolfssl configure
      working-directory: ./wolfssl 
      run: ./configure --enable-wolfclu --enable-crl --enable-dsa  --prefix=$GITHUB_WORKSPACE/build-dir
    - name: wolfssl make
      working-directory: ./wolfssl
      run: make
    - name: wolfssl make install
      working-directory: ./wolfssl
      run: make install

    - name: Upload built lib
      uses: actions/upload-artifact@v3
      with:
        name: wolf-install-wolfCLU
        path: build-dir
        retention-days: 1


    - uses: actions/checkout@master

    - name: Download lib
      uses: actions/download-artifact@v3
      with:
        name: wolf-install-wolfCLU
        path: build-dir
    - name: Check wolfSSL install dir
      run: ls $GITHUB_WORKSPACE/build-dir

    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --with-wolfssl=$GITHUB_WORKSPACE/build-dir
    - name: make
      run: make
    - name: make check
      run: make check
    - name: display log
      if: always()
      run: cat test-suite.log
